### ISSUE TITLE
Can't write to my gist...

### ISSUE THREAD

**Issue by tig** [simon-k/dotnet-code-coverage-badge#6]
I'm Getting `result:{"message":"Bad credentials","documentation_url"}` when trying to write to my gist

I don't have ownership of the project's github account so I had to ask the owner to set up the gist. He's double-checked to ensure it is set up correctly with the auth token in `secrets.GIST_AUTH_TOKEN`.

Can you see if I've got something mis-configured?

```yaml
name: Build Terminal.Gui with .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"  --settings UnitTests/coverlet.runsettings
        mv -v UnitTests/TestResults/*/*.* UnitTests/TestResults/

    - name: Create Test Coverage Badge
      uses: simon-k/dotnet-code-coverage-badge@v1.0.0
      id: create_coverage_badge
      with:
        label: Unit Test Coverage
        color: brightgreen
        path: UnitTests/TestResults/coverage.opencover.xml
        gist-filename: code-coverage.json
        # https://gist.github.com/migueldeicaza/90ef67a684cb71db1817921a970f8d27
        gist-id: 90ef67a684cb71db1817921a970f8d27
        gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}   

    - name: Print Code Coverage
      run: |
        echo "Code coverage percentage: ${{steps.create_coverage_badge.outputs.percentage}}%"
        echo "Badge data: ${{steps.create_coverage_badge.outputs.badge}}"
```

Here's my CI/CD output. As you can see, CC is being generated correctly.

![image](https://user-images.githubusercontent.com/585482/116002157-3ad69a00-a5ad-11eb-94af-1c38ec3c1d36.png)

Here's the gist: https://gist.github.com/migueldeicaza/90ef67a684cb71db1817921a970f8d27

What could be causing the "Bad Credentials"?

Thanks.
